//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSApplicationDelegate.h"

@class GBAboutUsWindow, GBSettingWindow, NSString, NSWindow;

@interface AppDelegate : NSObject <NSApplicationDelegate>
{
    GBAboutUsWindow *_aboutUsWindow;
    GBSettingWindow *_setWindow;
    NSWindow *_window;
}

+ (id)getMyMainWidown;
- (void).cxx_destruct;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)checkUpdates:(id)arg1;
- (void)setWidown:(id)arg1;
- (void)abutUs:(id)arg1;
- (void)comeApp;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

