//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSMutableDictionary;

@interface FDownLoaderManager : NSObject <NSCopying, NSMutableCopying>
{
    NSMutableDictionary *_downLoaderInfo;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *downLoaderInfo; // @synthesize downLoaderInfo=_downLoaderInfo;
- (void)resumeAll;
- (void)pauseAll;
- (void)cancleWithURL:(id)arg1;
- (void)resumeWithURL:(id)arg1;
- (void)pauseWithURL:(id)arg1;
- (void)downLoader:(id)arg1 downLoadInfo:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failed:(CDUnknownBlockType)arg5;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

