//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FFileTool : NSObject
{
}

+ (void)removeFile:(id)arg1;
+ (void)moveFile:(id)arg1 toPath:(id)arg2;
+ (long long)fileSize:(id)arg1;
+ (BOOL)fileExists:(id)arg1;

@end

