//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class GBAuthorWindown, NSTextField;

@interface GBAboutUsWindow : NSWindowController
{
    GBAuthorWindown *_authorWindown;
    NSTextField *_lableText;
}

- (void).cxx_destruct;
@property __weak NSTextField *lableText; // @synthesize lableText=_lableText;
- (void)UserServiceProtocol:(id)arg1;
- (void)close:(id)arg1;
- (void)goAuter:(id)arg1;
- (void)checkUpdates:(id)arg1;
- (void)windowDidLoad;

@end

