//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAlert.h"

@interface GBAlert : NSAlert
{
}

+ (void)alterTitle:(id)arg1 buttons:(id)arg2 widown:(id)arg3 comblock:(CDUnknownBlockType)arg4;

@end

