//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GBConHtmlRequest : NSObject
{
}

+ (void)htmlUserStateBlocksuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (id)returnHtmlDict;
+ (void)htmlLogOutHtmlBlocksuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)htmlLoginHtml:(id)arg1 Blocksuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;

@end

