//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSComboBoxDelegate.h"

@class GBCustemButton, GBDownLoadWindown, GBMyTextField, NSMutableArray, NSString, NSTextField;

@interface GBConnectView : NSView <NSComboBoxDelegate>
{
    NSMutableArray *_tArray;
    NSMutableArray *_cArray;
    NSView *_cView;
    NSView *_tView;
    NSTextField *_timeLable;
    GBMyTextField *_gbView;
    GBCustemButton *_wifiBtn;
    GBDownLoadWindown *_downLoadWindown;
    long long _selectIndex;
}

+ (void)voluntaryRenew:(BOOL)arg1;
+ (id)shareConnectView;
- (void).cxx_destruct;
@property(nonatomic) long long selectIndex; // @synthesize selectIndex=_selectIndex;
@property(retain, nonatomic) GBDownLoadWindown *downLoadWindown; // @synthesize downLoadWindown=_downLoadWindown;
- (void)btnClick:(id)arg1;
- (void)gotoLoginAction;
- (BOOL)checkNumAndPhone;
- (void)comboBoxSelectionIsChanging:(id)arg1;
- (void)comboBoxWillPopUp:(id)arg1;
- (void)saveNamePhone;
- (void)rzClick:(id)arg1;
- (void)screBtn:(id)arg1;
- (void)createTimeView;
- (void)creatContView;
- (void)creatView;
- (void)updateNetState:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

