//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SRPingHelperDelegate.h"

@class GBNetState, NSString, NSTimer, SRPingHelper;

@interface GBConnectChange : NSObject <SRPingHelperDelegate>
{
    BOOL _loginTime;
    BOOL _isAutoConBool;
    BOOL _isLogin;
    int _onlineTime;
    GBNetState *_netState;
    NSTimer *_wifiTimeTimer;
    NSString *_resUrl;
    SRPingHelper *_pingHelper;
}

+ (id)onlineTimeChangeStr;
+ (void)notNetWork;
+ (void)notNetWork:(BOOL)arg1;
+ (void)successNetWork:(BOOL)arg1;
+ (void)needWebAuthenticationiswifi:(BOOL)arg1;
+ (void)carChange;
+ (void)notNetSucessWork;
+ (id)getSFUrl;
+ (id)shareChange;
- (void).cxx_destruct;
@property(retain, nonatomic) SRPingHelper *pingHelper; // @synthesize pingHelper=_pingHelper;
@property(copy, nonatomic) NSString *resUrl; // @synthesize resUrl=_resUrl;
@property(nonatomic) BOOL isLogin; // @synthesize isLogin=_isLogin;
@property(nonatomic) BOOL isAutoConBool; // @synthesize isAutoConBool=_isAutoConBool;
@property(nonatomic) BOOL loginTime; // @synthesize loginTime=_loginTime;
@property(nonatomic) int onlineTime; // @synthesize onlineTime=_onlineTime;
@property(nonatomic) NSTimer *wifiTimeTimer; // @synthesize wifiTimeTimer=_wifiTimeTimer;
@property(retain, nonatomic) GBNetState *netState; // @synthesize netState=_netState;
- (void)updateInterfaceWithReachability:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)checkReachability;
- (void)onlineTimeChange;
- (void)timeStarting;
- (void)timeInval;
- (void)userLogOut;
- (void)userLogOutApp;
- (void)bindPhoneNum;
- (void)alterRecode:(int)arg1 result:(id)arg2;
- (void)loginAction:(id)arg1;
- (void)didReportSequence:(unsigned long long)arg1 timeout:(BOOL)arg2 delay:(double)arg3 resevict:(double)arg4 packetLoss:(double)arg5 hostIP:(id)arg6 packetlength:(long long)arg7;
- (void)retureSucess:(BOOL)arg1 hostIP:(id)arg2;
- (void)pingRsult;
- (void)potalUserState:(id)arg1 netState:(BOOL)arg2;
- (void)htmlLoginAction:(id)arg1;
- (void)toSuccessMin;
- (void)backPotalUserState;
- (void)identCheak;
- (void)backChecknetWork;
- (void)backGatewayChecknetWork;
- (void)checkNetWork;
- (void)gatewayChecknetWork;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)jumpViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

