//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSColor;

@interface GBCustemButton : NSButton
{
    NSColor *_textColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
- (void)drawRect:(struct CGRect)arg1;

@end

