//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@interface GBDownLoadWindown : NSWindowController
{
}

- (void)openDownGiwifiFile:(id)arg1;
- (void)downLoad:(id)arg1 totalSize:(long long)arg2 view:(id)arg3;
- (void)windowDidLoad;

@end

