//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GBEncryptionMethod : NSObject
{
}

+ (id)returnBase64Dencode:(id)arg1;
+ (id)returnBase64Encode:(id)arg1;
+ (id)dencryptStr:(id)arg1 key:(id)arg2;
+ (id)encryptStr:(id)arg1 key:(id)arg2;
+ (id)aes256_decrypt:(id)arg1 data:(id)arg2;
+ (id)dencryAceStr:(id)arg1 base64:(BOOL)arg2;
+ (id)aes256_encrypt:(id)arg1 data:(id)arg2;
+ (id)encryAceStr:(id)arg1;

@end

