//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GBHttpRequest : NSObject
{
}

+ (void)isFailCheck;
+ (void)paramaterNetWorkGetDict:(id)arg1;
+ (void)userCheckNetWork:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)voluntaryRenew:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)userDataAnyThingStr:(id)arg1 comblock:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (void)userAuthentication:(id)arg1 comblock:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (void)userCheck:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)bindMac:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)userOfflineAction:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;

@end

