//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSTextField;

@interface GBMyTextField : NSView
{
    NSTextField *_textField;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *textField; // @synthesize textField=_textField;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 imageName:(id)arg2;

@end

