//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GBNetInformation : NSObject
{
}

+ (void)canleInfo;
+ (BOOL)isOurPotalWifi;
+ (id)getIPWithHostName:(id)arg1;
+ (id)getWareIPaddr:(id)arg1;
+ (id)getDeviceMacAddress:(id)arg1;
+ (id)deviceIPAdress:(id)arg1;
+ (id)getMacInformation;

@end

