//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface GBNetState : NSObject
{
    NSString *_wifiStateStr;
    NSString *_wifiTimeStr;
    NSString *_wifiBtnStr;
    NSString *_GbtnState;
    NSString *_rzStyle;
    NSString *_enkStr;
    NSDictionary *_enkDict;
}

+ (void)destroyInstance;
+ (id)shareState;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *enkDict; // @synthesize enkDict=_enkDict;
@property(copy, nonatomic) NSString *enkStr; // @synthesize enkStr=_enkStr;
@property(copy, nonatomic) NSString *rzStyle; // @synthesize rzStyle=_rzStyle;
@property(copy, nonatomic) NSString *GbtnState; // @synthesize GbtnState=_GbtnState;
@property(copy, nonatomic) NSString *wifiBtnStr; // @synthesize wifiBtnStr=_wifiBtnStr;
@property(copy, nonatomic) NSString *wifiTimeStr; // @synthesize wifiTimeStr=_wifiTimeStr;
@property(copy, nonatomic) NSString *wifiStateStr; // @synthesize wifiStateStr=_wifiStateStr;

@end

