//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton;

@interface GBSettingWindow : NSWindowController
{
    NSButton *_narrow;
}

- (void).cxx_destruct;
@property __weak NSButton *narrow; // @synthesize narrow=_narrow;
- (void)narrow:(id)arg1;
- (void)confirm:(id)arg1;
- (void)cancel:(id)arg1;
- (void)windowDidLoad;

@end

