//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GBTool : NSObject
{
}

+ (id)getMacString:(id)arg1;
+ (BOOL)isPotal;
+ (id)getStationAdress;
+ (id)getPotalIpAdress;
+ (id)getChallenge:(id)arg1 szKey:(id)arg2;
+ (id)getPotalStationAdress;
+ (id)getMacVersion;
+ (id)doAppleScript:(id)arg1;
+ (id)getServriceIDByBSD:(id)arg1;
+ (id)ServriceIDict;
+ (id)reurnEnk;
+ (void)installTool;
+ (BOOL)returnSavePassword;
+ (id)getUserStandValue:(id)arg1 valueClass:(Class)arg2;
+ (BOOL)setCurentCard:(id)arg1;
+ (id)getEnk:(id)arg1;
+ (id)getNetCardAllInfo;
+ (id)buildVerSion;
+ (id)appVersion;
+ (void)openUrl:(id)arg1;
+ (id)pxDict:(id)arg1;
+ (id)getCurrentTime;
+ (id)getUUID;
+ (BOOL)reurnLoginBool;

@end

