//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSMutableArray;

@interface GBTopView : NSView
{
    NSMutableArray *_bArray;
}

+ (void)showBtn;
+ (void)hidenBtn;
+ (id)sharetopView;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *bArray; // @synthesize bArray=_bArray;
- (void)btnClick:(id)arg1;
- (void)creatView;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

