//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"
#import "NSURLSessionTaskDelegate.h"
#import "SRPingHelperDelegate.h"

@class NSMutableData, NSString, NSURLConnection, NSURLSessionDataTask, SRPingHelper;

@interface GBWiFiCheck : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate, SRPingHelperDelegate>
{
    NSURLSessionDataTask *_task;
    NSMutableData *_mData;
    NSURLConnection *_connection;
    CDUnknownBlockType _netBlock;
    SRPingHelper *_pingHelper;
}

+ (id)shareWiFiCheck;
- (void).cxx_destruct;
@property(retain, nonatomic) SRPingHelper *pingHelper; // @synthesize pingHelper=_pingHelper;
@property(copy, nonatomic) CDUnknownBlockType netBlock; // @synthesize netBlock=_netBlock;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableData *mData; // @synthesize mData=_mData;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
- (void)jxMethod:(int)arg1;
- (void)retureSucess:(BOOL)arg1 hostIP:(id)arg2;
- (void)pingRsult;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)startNetWork;
- (void)removeCache;
- (void)checkNetWork;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

