//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (YW)
- (id)URLEncode;
- (id)stringFromMD5;
- (id)enmyStr;
- (id)URLEncodedString;
- (id)URLDecodedString;
- (id)denmyStrBsee64:(BOOL)arg1;
- (id)jsonDict;
- (id)paramValueOfUrl:(id)arg1;
- (id)trimming;
@end

