//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol SRPingHelperDelegate <NSObject>
- (void)retureSucess:(BOOL)arg1 hostIP:(NSString *)arg2;
- (void)didReportSequence:(unsigned long long)arg1 timeout:(BOOL)arg2 delay:(double)arg3 resevict:(double)arg4 packetLoss:(double)arg5 hostIP:(NSString *)arg6 packetlength:(long long)arg7;
@end

