//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimplePingDelegate.h"

@class NSObject<OS_dispatch_queue>, NSString, NSTimer, SimplePing;

@interface SRPingHelper : NSObject <SimplePingDelegate>
{
    id <SRPingHelperDelegate> _delegate;
    double _delay;
    double _packetLoss;
    NSString *_host;
    NSString *_hostIP;
    double _startTimeInterval;
    unsigned long long _sendPackets;
    unsigned long long _receivePackets;
    NSTimer *_pingTimer;
    SimplePing *_simplePing;
    NSObject<OS_dispatch_queue> *_ping_queue;
}

+ (id)displayAddressForAddress:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *ping_queue; // @synthesize ping_queue=_ping_queue;
@property(retain, nonatomic) SimplePing *simplePing; // @synthesize simplePing=_simplePing;
@property(retain, nonatomic) NSTimer *pingTimer; // @synthesize pingTimer=_pingTimer;
@property(nonatomic) unsigned long long receivePackets; // @synthesize receivePackets=_receivePackets;
@property(nonatomic) unsigned long long sendPackets; // @synthesize sendPackets=_sendPackets;
@property(nonatomic) double startTimeInterval; // @synthesize startTimeInterval=_startTimeInterval;
@property(copy, nonatomic) NSString *hostIP; // @synthesize hostIP=_hostIP;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(nonatomic) double packetLoss; // @synthesize packetLoss=_packetLoss;
@property(nonatomic) double delay; // @synthesize delay=_delay;
@property(nonatomic) __weak id <SRPingHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void)clearSimplePing;
- (void)pingTimeout;
- (void)doPing;
- (void)simplePing:(id)arg1 didReceiveUnexpectedPacket:(id)arg2;
- (id)displayAddressForAddress:(id)arg1;
- (void)simplePing:(id)arg1 didReceivePingResponsePacket:(id)arg2 sequenceNumber:(unsigned short)arg3;
- (void)simplePing:(id)arg1 didFailToSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3 error:(id)arg4;
- (void)simplePing:(id)arg1 didSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3;
- (void)simplePing:(id)arg1 didFailWithError:(id)arg2;
- (void)simplePing:(id)arg1 didStartWithAddress:(id)arg2;
- (void)stopPing;
- (void)startOnePing;
- (void)startPing;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

